data_dir: "data/processed"
train_dir: "data/train"
test_dir: "data/test"
model_path: "models/jewellery_model.pth"
image_size: 224
batch_size: 32
num_epochs: 10
learning_rate: 0.001
classes: ["ring", "bracelet", "necklace", "earrings"]
