# config.yaml

image_size: [224, 224]

data_paths:
  raw: data/raw
  output: data

split_ratio:
  train: 0.7
  val: 0.15
  test: 0.15

valid_extensions: [".jpg", ".jpeg", ".png"]

augmentation:
  train:
    horizontal_flip: true
    rotation: 15     # degrees
    color_jitter: true
